image: gitpod/workspace-full
tasks:
  - init: npm install -g
    command: . ./gitpod-setup.sh && npm start
ports:
  - port: 8001
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false
